---
- hosts: localhost
  gather_facts: false
  name: Setup ONTAP
  vars:
    hostname: xxx.xxx.xxx.xxx
    username: username
    password: password
    volname: test007
    vserver: Ansible_Handson
    aggr: aggr1_node1
    address: xxx.xxx.xxx.xxx(lif ip)
    policy: ansiblePolicy
    state: present
  tasks:
  - name: Create Policy
    na_ontap_export_policy:
      state: "{{ state }}"
      name: "{{ policy }}"
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
  - name: Setup rules
    na_ontap_export_policy_rule:
      state: "{{ state }}"
      policy_name: "{{ policy }}"
      vserver: "{{ vserver }}"
      client_match: 0.0.0.0/0
      ro_rule: any
      rw_rule: any
      super_user_security: any
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
  - name: Create volume
    na_ontap_volume:
      state: "{{ state }}"
      name: "{{ volname }}"
      aggregate_name: "{{ aggr }}"
      size: 15
      size_unit: gb
      policy: "{{ policy }}"
      junction_path: "/{{ volname }}"
      space_guarantee: "none"
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"

- hosts: ansible-server
  vars:
    address: xxx.xxx.xxx.xxx(host ip)
    volname: test007
  tasks:
  - name: Install NFS-UTILS package for Client Server
    yum: name=nfs-utils state=present

  - name: Update fstab file
    lineinfile:
      path: /etc/fstab
      line: "{{ address }}:/{{ volname }} /srv nfs defaults 0 0"
  - name: Verify mount directory exists
    file:
      path: /srv
      state: directory
  - name: Mount nfs export
    mount:
      state: mounted
      path: /srv
      src: "{{ address }}:/{{ volname }}"
      fstype: nfs
...
