---
- hosts: localhost
  gather_facts: false
  name: Setup ONTAP
  vars:
    hostname: 49.254.105.140
    username: admin
    password: Netapp123
    vserver: cds_test
    volname1: mysql_data
    volname2: wordpress_data
    aggr: aggr1_node1
    address: 49.254.105.221
    policy: ansiblePolicy
    state: present
  tasks:
  - name: Create Policy
    na_ontap_export_policy:
      state: "{{ state }}"
      name: "{{ policy }}"
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
  - name: Setup rules
    na_ontap_export_policy_rule:
      state: "{{ state }}"
      policy_name: "{{ policy }}"
      vserver: "{{ vserver }}"
      client_match: 0.0.0.0/0
      ro_rule: any
      rw_rule: any
      super_user_security: any
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
  - name: Create volume_1
    na_ontap_volume:
      state: "{{ state }}"
      name: "{{ volname1 }}"
      aggregate_name: "{{ aggr }}"
      size: 15
      size_unit: gb
      policy: "{{ policy }}"
      junction_path: "/{{ volname1 }}"
      space_guarantee: "none"
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
  - name: Create volume_2
    na_ontap_volume:
      state: "{{ state }}"
      name: "{{ volname2 }}"
      aggregate_name: "{{ aggr }}"
      size: 15
      size_unit: gb
      policy: "{{ policy }}"
      junction_path: "/{{ volname2 }}"
      space_guarantee: "none"
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"


- hosts: jumphost
  vars:
    jumphostname: 49.254.105.77
    jumphostusername: root
    jumphostpassword: Netapp123!
    volname1: mysql_data
    volname2: wordpress_data
  tasks:
  - name: Install NFS-UTILS package for Client Server
    yum: name=nfs-utils state=present
    hostname: "{{ jumphostname }}"
    username: "{{jumphostusername }}"
    password: "{{ jumphostpassword }}"
  - name: Update fstab file for mysql
    lineinfile:
      path: /etc/fstab
      line: "{{ address }}:/{{ volname1 }} /var/lib/mysql nfs defaults 0 0"
  - name: Update fstab file for wordpress
    lineinfile:
      path: /etc/fstab
      line: "{{ address }}:/{{ volname2 }} /var/www/html nfs defaults 0 0"
  - name: Verify mount directory exists for mysql data
    file:
      path: /var/lib/mysql
      state: directory
  - name: Verify mount directory exists for wordpress core file
    file:
      path: /var/www/html
      state: directory
  - name: Mount nfs export for vol1
    mount:
      state: mounted
      path: /var/lib/mysql
      src: "{{ address }}:/{{ volname1 }}"
      fstype: nfs
  - name: Mount nfs export for vol2
    mount:
      state: mounted
      path: /var/www/html
      src: "{{ address }}:/{{ volname2 }}"
      fstype: nfs
...
